packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  workerd: true

catalog:
  "@tanstack/react-query": 5.102.8
  "@tanstack/react-router": 1.170.32
  "@tanstack/react-start": 1.168.49
  react: 19.2.8
  react-dom: 19.2.8
  typescript: 7.0.2
  vitest: 4.1.11
  zod: 4.5.1

minimumReleaseAgeExclude:
  - "@cloudflare/workerd-darwin-64@1.20260828.1"
  - "@cloudflare/workerd-darwin-arm64@1.20260828.1"
  - "@cloudflare/workerd-linux-64@1.20260828.1"
  - "@cloudflare/workerd-linux-arm64@1.20260828.1"
  - "@cloudflare/workerd-windows-64@1.20260828.1"
  - "@cloudflare/workers-types@5.20260828.1"
  - "@vitejs/plugin-react@6.1.1"
  - miniflare@5.20260828.0-alpha
  - workerd@1.20260828.1
  - wrangler@4.127.1
  - zod@4.5.1
  - "@cloudflare/vite-plugin@1.54.2"
