/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdaptersRouteImport } from './routes/adapters'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as FeatureFlagsRouteImport } from './routes/feature-flags'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembershipDomainsRouteImport } from './routes/membership-domains'
import { Route as ModelRoutingRouteImport } from './routes/model-routing'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as OperatorsRouteImport } from './routes/operators'
import { Route as SecretsRouteImport } from './routes/secrets'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiSplatRouteImport } from './routes/api.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptersRoute = AdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureFlagsRoute = FeatureFlagsRouteImport.update({
  id: '/feature-flags',
  path: '/feature-flags',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipDomainsRoute = MembershipDomainsRouteImport.update({
  id: '/membership-domains',
  path: '/membership-domains',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoutingRoute = ModelRoutingRouteImport.update({
  id: '/model-routing',
  path: '/model-routing',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsRoute = OperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretsRoute = SecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/audit': typeof AuditRoute
  '/feature-flags': typeof FeatureFlagsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/membership-domains': typeof MembershipDomainsRoute
  '/model-routing': typeof ModelRoutingRoute
  '/models': typeof ModelsRoute
  '/operators': typeof OperatorsRoute
  '/secrets': typeof SecretsRoute
  '/settings': typeof SettingsRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/audit': typeof AuditRoute
  '/feature-flags': typeof FeatureFlagsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/membership-domains': typeof MembershipDomainsRoute
  '/model-routing': typeof ModelRoutingRoute
  '/models': typeof ModelsRoute
  '/operators': typeof OperatorsRoute
  '/secrets': typeof SecretsRoute
  '/settings': typeof SettingsRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/audit': typeof AuditRoute
  '/feature-flags': typeof FeatureFlagsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/membership-domains': typeof MembershipDomainsRoute
  '/model-routing': typeof ModelRoutingRoute
  '/models': typeof ModelsRoute
  '/operators': typeof OperatorsRoute
  '/secrets': typeof SecretsRoute
  '/settings': typeof SettingsRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adapters'
    | '/audit'
    | '/feature-flags'
    | '/integrations'
    | '/login'
    | '/membership-domains'
    | '/model-routing'
    | '/models'
    | '/operators'
    | '/secrets'
    | '/settings'
    | '/api/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adapters'
    | '/audit'
    | '/feature-flags'
    | '/integrations'
    | '/login'
    | '/membership-domains'
    | '/model-routing'
    | '/models'
    | '/operators'
    | '/secrets'
    | '/settings'
    | '/api/$'
  id:
    | '__root__'
    | '/'
    | '/adapters'
    | '/audit'
    | '/feature-flags'
    | '/integrations'
    | '/login'
    | '/membership-domains'
    | '/model-routing'
    | '/models'
    | '/operators'
    | '/secrets'
    | '/settings'
    | '/api/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdaptersRoute: typeof AdaptersRoute
  AuditRoute: typeof AuditRoute
  FeatureFlagsRoute: typeof FeatureFlagsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  MembershipDomainsRoute: typeof MembershipDomainsRoute
  ModelRoutingRoute: typeof ModelRoutingRoute
  ModelsRoute: typeof ModelsRoute
  OperatorsRoute: typeof OperatorsRoute
  SecretsRoute: typeof SecretsRoute
  SettingsRoute: typeof SettingsRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adapters': {
      id: '/adapters'
      path: '/adapters'
      fullPath: '/adapters'
      preLoaderRoute: typeof AdaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feature-flags': {
      id: '/feature-flags'
      path: '/feature-flags'
      fullPath: '/feature-flags'
      preLoaderRoute: typeof FeatureFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership-domains': {
      id: '/membership-domains'
      path: '/membership-domains'
      fullPath: '/membership-domains'
      preLoaderRoute: typeof MembershipDomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-routing': {
      id: '/model-routing'
      path: '/model-routing'
      fullPath: '/model-routing'
      preLoaderRoute: typeof ModelRoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secrets': {
      id: '/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof SecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdaptersRoute: AdaptersRoute,
  AuditRoute: AuditRoute,
  FeatureFlagsRoute: FeatureFlagsRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  MembershipDomainsRoute: MembershipDomainsRoute,
  ModelRoutingRoute: ModelRoutingRoute,
  ModelsRoute: ModelsRoute,
  OperatorsRoute: OperatorsRoute,
  SecretsRoute: SecretsRoute,
  SettingsRoute: SettingsRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
