/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdaptersRouteImport } from './routes/_authenticated/adapters'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedFeatureFlagsRouteImport } from './routes/_authenticated/feature-flags'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedMembershipDomainsRouteImport } from './routes/_authenticated/membership-domains'
import { Route as AuthenticatedModelRoutingRouteImport } from './routes/_authenticated/model-routing'
import { Route as AuthenticatedModelsRouteImport } from './routes/_authenticated/models'
import { Route as AuthenticatedOperatorsRouteImport } from './routes/_authenticated/operators'
import { Route as AuthenticatedSecretsRouteImport } from './routes/_authenticated/secrets'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiSplatRouteImport } from './routes/api.$'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdaptersRoute = AuthenticatedAdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeatureFlagsRoute =
  AuthenticatedFeatureFlagsRouteImport.update({
    id: '/feature-flags',
    path: '/feature-flags',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembershipDomainsRoute =
  AuthenticatedMembershipDomainsRouteImport.update({
    id: '/membership-domains',
    path: '/membership-domains',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedModelRoutingRoute =
  AuthenticatedModelRoutingRouteImport.update({
    id: '/model-routing',
    path: '/model-routing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedModelsRoute = AuthenticatedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperatorsRoute = AuthenticatedOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecretsRoute = AuthenticatedSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/adapters': typeof AuthenticatedAdaptersRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/feature-flags': typeof AuthenticatedFeatureFlagsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/membership-domains': typeof AuthenticatedMembershipDomainsRoute
  '/model-routing': typeof AuthenticatedModelRoutingRoute
  '/models': typeof AuthenticatedModelsRoute
  '/operators': typeof AuthenticatedOperatorsRoute
  '/secrets': typeof AuthenticatedSecretsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/adapters': typeof AuthenticatedAdaptersRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/feature-flags': typeof AuthenticatedFeatureFlagsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/membership-domains': typeof AuthenticatedMembershipDomainsRoute
  '/model-routing': typeof AuthenticatedModelRoutingRoute
  '/models': typeof AuthenticatedModelsRoute
  '/operators': typeof AuthenticatedOperatorsRoute
  '/secrets': typeof AuthenticatedSecretsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/adapters': typeof AuthenticatedAdaptersRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/feature-flags': typeof AuthenticatedFeatureFlagsRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/membership-domains': typeof AuthenticatedMembershipDomainsRoute
  '/_authenticated/model-routing': typeof AuthenticatedModelRoutingRoute
  '/_authenticated/models': typeof AuthenticatedModelsRoute
  '/_authenticated/operators': typeof AuthenticatedOperatorsRoute
  '/_authenticated/secrets': typeof AuthenticatedSecretsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/adapters'
    | '/audit'
    | '/customers'
    | '/feature-flags'
    | '/integrations'
    | '/membership-domains'
    | '/model-routing'
    | '/models'
    | '/operators'
    | '/secrets'
    | '/settings'
    | '/api/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/adapters'
    | '/audit'
    | '/customers'
    | '/feature-flags'
    | '/integrations'
    | '/membership-domains'
    | '/model-routing'
    | '/models'
    | '/operators'
    | '/secrets'
    | '/settings'
    | '/api/$'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/adapters'
    | '/_authenticated/audit'
    | '/_authenticated/customers'
    | '/_authenticated/feature-flags'
    | '/_authenticated/integrations'
    | '/_authenticated/membership-domains'
    | '/_authenticated/model-routing'
    | '/_authenticated/models'
    | '/_authenticated/operators'
    | '/_authenticated/secrets'
    | '/_authenticated/settings'
    | '/api/$'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/adapters': {
      id: '/_authenticated/adapters'
      path: '/adapters'
      fullPath: '/adapters'
      preLoaderRoute: typeof AuthenticatedAdaptersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feature-flags': {
      id: '/_authenticated/feature-flags'
      path: '/feature-flags'
      fullPath: '/feature-flags'
      preLoaderRoute: typeof AuthenticatedFeatureFlagsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membership-domains': {
      id: '/_authenticated/membership-domains'
      path: '/membership-domains'
      fullPath: '/membership-domains'
      preLoaderRoute: typeof AuthenticatedMembershipDomainsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/model-routing': {
      id: '/_authenticated/model-routing'
      path: '/model-routing'
      fullPath: '/model-routing'
      preLoaderRoute: typeof AuthenticatedModelRoutingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/models': {
      id: '/_authenticated/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operators': {
      id: '/_authenticated/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof AuthenticatedOperatorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/secrets': {
      id: '/_authenticated/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof AuthenticatedSecretsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdaptersRoute: typeof AuthenticatedAdaptersRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedFeatureFlagsRoute: typeof AuthenticatedFeatureFlagsRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedMembershipDomainsRoute: typeof AuthenticatedMembershipDomainsRoute
  AuthenticatedModelRoutingRoute: typeof AuthenticatedModelRoutingRoute
  AuthenticatedModelsRoute: typeof AuthenticatedModelsRoute
  AuthenticatedOperatorsRoute: typeof AuthenticatedOperatorsRoute
  AuthenticatedSecretsRoute: typeof AuthenticatedSecretsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdaptersRoute: AuthenticatedAdaptersRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedFeatureFlagsRoute: AuthenticatedFeatureFlagsRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedMembershipDomainsRoute: AuthenticatedMembershipDomainsRoute,
  AuthenticatedModelRoutingRoute: AuthenticatedModelRoutingRoute,
  AuthenticatedModelsRoute: AuthenticatedModelsRoute,
  AuthenticatedOperatorsRoute: AuthenticatedOperatorsRoute,
  AuthenticatedSecretsRoute: AuthenticatedSecretsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
